version: "3.6"
x-common-variables: &common-variables
  NODE_ENV: local
  DB_MAIN_HOST: mysql
  DB_MAIN_USER: root
  DB_MAIN_PASS: root
  DB_MAIN_NAME: main_db
  AWS_ACCESS_KEY_ID: anykey
  AWS_SECRET_ACCESS_KEY: anysecret
  AWS_REGION: us-east-2
services:
  local:
    build:
      context: .
    image: plataforma5-backend
    volumes:
      - ./src:/app/src
    container_name: plataforma5-backend_local
    environment: *common-variables
    depends_on:
      - mysql
    ports:
      - "3000:3000"
      - "9229:9229"
    networks:
      - default
    tty: true
    entrypoint: ["npm", "run", "local"]
  test:
    build:
      context: .
    image: plataforma5-backend
    volumes:
      - ./src:/app/src
      - ./coverage/unit:/app/coverage
    container_name: plataforma5-backend_test
    environment: *common-variables
    tty: true
    entrypoint: ["npm", "test"]
  integration-test:
    build:
      context: .
    image: plataforma5-backend
    volumes:
      - ./src:/app/src
      - ./coverage/integration:/app/coverage
    container_name: plataforma5-backend_integration
    environment:
      <<: *common-variables
      NODE_ENV: test
    depends_on:
      - mysql
    tty: true
    entrypoint: ["npm", "run", "integration"]
  mysql:
    image: mysql:5.7
    container_name: plataforma5-database_mysql
    ports:
      - 3306:3306
    volumes:
      - ./db/schema-test.sql:/docker-entrypoint-initdb.d/schema-test.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: test
      MYSQL_PASSWORD: testpass
  localstack:
    image:  localstack/localstack:0.11.4
    container_name: plataforma5_localstack
    ports:
      - "4568-4576:4568-4576"
      - "8080:8080"
    environment:
      - SERVICES=sns:4575,sqs:4576
      - DEFAULT_REGION=us-east-2
  setup:
    image: mesosphere/aws-cli
    container_name: plataforma5_setup
    environment:
      - AWS_ACCESS_KEY_ID=AKIAEXAMPLE123
      - AWS_SECRET_ACCESS_KEY=AWSSECRETACCESSEY123
      - AWS_DEFAULT_REGION=us-east-2
    entrypoint: /bin/sh -c
    command: >
      "
        sleep 7s
        # Executing SNS
        aws sns create-topic --name local_sns --endpoint-url=http://localstack:4575 
        # Executing SQS
        aws sqs create-queue --endpoint-url=http://localstack:4576 --queue-name notificaciones;
        # Executing SQS
        aws sqs create-queue --endpoint-url=http://localstack:4576 --queue-name estadisticas;
      "
    depends_on:
      - localstack
networks:
  default:
    name: plataforma5-backend

